In [12]:
import pandas as pd

In [13]:
# pandas has two core object series, dataframe

In [14]:
# series
pd.Series((1,2,2,3),name="Age")

0    1
1    2
2    2
3    3
Name: Age, dtype: int64

In [15]:
# dataframe 
# dict 
di={"Name":["anand","mango","pen","mobile"],
    "Identity":["human","fruit","object",None]
}

df=pd.DataFrame(di)

print(type(df))

<class 'pandas.DataFrame'>

In [16]:
df.head(2)

    Name Identity
0  anand    human
1  mango    fruit

In [17]:
df.tail(2)

     Name Identity
2     pen   object
3  mobile      NaN

In [18]:
df.sample()

    Name Identity
0  anand    human

In [19]:
df.head()

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile      NaN

In [20]:
type(df["Name"])

pandas.Series

In [22]:
df[["Name","Identity"]]

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile      NaN

In [27]:
df = df.drop(columns=["count"])

count = [1, 10, 3, 2]
df.insert(0, "count", count)

print(df)

   count    Name Identity
0      1   anand    human
1     10   mango    fruit
2      3     pen   object
3      2  mobile      NaN

In [29]:
colour = "skin","orange","blue","black"

In [31]:
df["color"] =colour

In [32]:
df["id"] =[1,2,3,4]

In [33]:
df.sample()

   count Name Identity color  id
2      3  pen   object  blue   3

In [34]:
df2 = pd.DataFrame({
    'id': [1, 2, 6, 4,5],
    'weight': [55, 62, 48, 70,None]
})

print(df2)

   id  weight
0   1    55.0
1   2    62.0
2   6    48.0
3   4    70.0
4   5     NaN

In [35]:
# merge or join
pd.merge(df,df2, how="left",on="id")

   count    Name Identity   color  id  weight
0      1   anand    human    skin   1    55.0
1     10   mango    fruit  orange   2    62.0
2      3     pen   object    blue   3     NaN
3      2  mobile      NaN   black   4    70.0

In [37]:
pd.merge(df,df2)  # sets

   count    Name Identity   color  id  weight
0      1   anand    human    skin   1    55.0
1     10   mango    fruit  orange   2    62.0
2      2  mobile      NaN   black   4    70.0